In [1]:
import sys
sys.path.insert(0, "..")

from src.charger import charger_prenoms
from src.nettoyer import nettoyer_prenoms
from src.indicateurs import serie_prenom

p = nettoyer_prenoms(charger_prenoms())

In [2]:
marie = serie_prenom(p, "Marie", 2)
print(marie.shape)
marie.head(3)

(126, 2)

       naissances  part_pour_10000
annee
1900        48695      2060.553487
1901        52125      2035.496720
1902        51835      1992.849042

In [3]:
aloys = serie_prenom(p, "Aloys", 1)
aloys.loc[1936:1945]

       naissances  part_pour_10000
annee
1936          5.0         0.174237
1937          5.0         0.176202
1938          5.0         0.177607
1939          NaN              NaN
1940          5.0         0.195084
1941         10.0         0.411049
1942          NaN              NaN
1943          5.0         0.171874
1944          5.0         0.170675
1945          NaN              NaN

In [2]:
from src.indicateurs import pic_et_minimum

print(pic_et_minimum(serie_prenom(p, "Marie", 2)))
print(pic_et_minimum(serie_prenom(p, "Aloys", 1)))

{'annee_pic': 1901, 'valeur_pic': 52125.0, 'annee_min': 2025, 'valeur_min': 510.0, 'annees_diffusees': 126, 'annees_absentes': 0}
{'annee_pic': 2009, 'valeur_pic': 70.0, 'annee_min': 1901, 'valeur_min': 5.0, 'annees_diffusees': 73, 'annees_absentes': 53}

In [2]:
from src.indicateurs import comparer_prenoms

duo = comparer_prenoms(p, [("MARIE", 2), ("LOUISE", 2)])
duo.loc[[1900, 1950, 2000, 2025]]

       MARIE (Féminin)  LOUISE (Féminin)
annee
1900       2060.553487        283.090724
1950        649.130349         11.967143
2000        169.177166         68.757204
2025         17.782737        107.045102

In [2]:
from src.indicateurs import top_par_decennie

top = top_par_decennie(p, sexe=2, n=3)
print(top.shape)
print(top.to_string())

(39, 5)
    decennie      prenom  naissances  rang_decennie  nb_annees
0       1900       MARIE      490380              1         10
1       1900      JEANNE      150240              2         10
2       1900  MARGUERITE       89435              3         10
3       1910       MARIE      329070              1         10
4       1910      JEANNE      121250              2         10
5       1910   MADELEINE       66625              3         10
6       1920       MARIE      322340              1         10
7       1920      JEANNE      127550              2         10
8       1920  JACQUELINE       81980              3         10
9       1930       MARIE      247405              1         10
10      1930     MONIQUE      112145              2         10
11      1930  JACQUELINE      108615              3         10
12      1940       MARIE      264725              1         10
13      1940     MONIQUE      139575              2         10
14      1940      NICOLE      120125              3         10
15      1950       MARIE      215875              1         10
16      1950     MARTINE      191465              2         10
17      1950   FRANÇOISE      126315              3         10
18      1960      SYLVIE      204750              1         10
19      1960    NATHALIE      197630              2         10
20      1960    ISABELLE      186470              3         10
21      1970    SANDRINE      146350              1         10
22      1970    NATHALIE      139645              2         10
23      1970   STÉPHANIE      135795              3         10
24      1980     AURÉLIE      113285              1         10
25      1980      EMILIE       92485              2         10
26      1980      CÉLINE       84670              3         10
27      1990       LAURA       69990              1         10
28      1990       MARIE       69685              2         10
29      1990     CAMILLE       67155              3         10
30      2000         LÉA       77355              1         10
31      2000        EMMA       66790              2         10
32      2000       MANON       62930              3         10
33      2010        EMMA       49105              1         10
34      2010        JADE       42830              2         10
35      2010      LOUISE       41660              3         10
36      2020      LOUISE       20370              1          6
37      2020        JADE       19910              2          6
38      2020       AMBRE       17940              3          6

In [2]:
from src.indicateurs import resume_periode

recent = resume_periode(p, 2016, 2025)
print(recent.shape)
recent.loc[[(2, "LOUISE"), (2, "MARIE"), (1, "GABRIEL")]]

(30712, 3)

              part_moyenne  naissances  annees_diffusees
sexe prenom
2    LOUISE     110.953746       36115                10
     MARIE       21.027903        6885                10
1    GABRIEL    144.766546       49730                10

In [2]:
from src.indicateurs import tendances

t = tendances(p)
print(t.shape)
t.loc[[(2, "LOUISE"), (2, "MARIE"), (1, "GABRIEL")]].round(2)

(21078, 8)

              part_moyenne_recente  naissances_recente  \
sexe prenom
2    LOUISE                 110.95               36115
     MARIE                   21.03                6885
1    GABRIEL                144.77               49730

              annees_diffusees_recente  part_moyenne_precedente  \
sexe prenom
2    LOUISE                         10                   103.17
     MARIE                          10                    50.64
1    GABRIEL                        10                   117.86

              naissances_precedente  annees_diffusees_precedente  \
sexe prenom
2    LOUISE                   38605                           10
     MARIE                    19070                           10
1    GABRIEL                  46565                           10

              variation_part  variation_pct
sexe prenom
2    LOUISE             7.78           7.54
     MARIE            -29.61         -58.47
1    GABRIEL           26.91          22.83